### ISSUE TITLE
[Proposal] Use custom css for checkboxes

### ISSUE THREAD

**Issue by AquaXV** [CodeMyst/VoteMyst#108]
## Description
Default HTML checkboxes look blunt and boring imo

## Suggested Implementations
I think the checkboxes can look nicer than default HTML by applying some CSS; little larger, rounded corners, more distinct border, T H I C C-er tick

**Comment by yiliansource** [comment]
Do you have an example of how they could look? @AquaXV

**Comment by yiliansource** [comment]
@AquaXV 

This is the current iteration of the visuals:

![image](https://user-images.githubusercontent.com/41469451/91144196-f4463e00-e6b3-11ea-8c12-91ba1c7f08ad.png)

I'd love to hear your feedback.
Additionally, checkboxes can now easily be created through the `<checkbox/>` tag, since plain HTML checkboxes can't really be styled by themselves.

**Comment by AquaXV** [comment]
I'd make the edges slightly less round; they now quite closely resemble radio buttons, and background a bit lighter to make it easier to see. Other than that seems fine to me
